language: python

cache:
  directories:
  - "$TRAVIS_BUILD_DIR/build/GSL/src"
  - "$HOME/miniconda"

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip
  - source activate test-environment

  - pip install numpy nose coveralls
  - pip install matplotlib scipy
  - pip install astropy astroquery
  - pip install scikit-image
  - pip install coloredlogs

install:
  - python setup.py install

before_script:
  - "export PYSYN_CDBS=tests/data/"
  - "echo backend: agg > matplotlibrc"
  - "wget -L http://www.libradtran.org/download/libRadtran-2.0.2.tar.gz"
  - "gzip -d libRadtran-2.0.2.tar.gz"
  - "tar -xvf libRadtran-2.0.2.tar"
  - "cd libRadtran-2.0.2"
  - "./configure"
  - "make"
  - "cd ../"
  - "export LIBRADTRANDIR=libRadtran-2.0.2/"

script:
  - nosetests tests/run_tests.py --all --debug --detailed-errors --verbose --process-restartworker --with-coverage --cover-package=spectractor
  - ./coverage_and_test.sh
#- coverage run -a --source=spectractor spectractor/*.py
#- coverage run -a --source=spectractor extractor simulator fit

after_success:
  - coveralls